---
timesync_ntp_servers:
  - hostname: 0.rhel.pool.ntp.org
    iburst: true
  - hostname: 1.rhel.pool.ntp.org
    iburst: true
  - hostname: 2.rhel.pool.ntp.org
    iburst: true
  - hostname: 3.rhel.pool.ntp.org
    iburst: true
selinux_policy: targeted
selinux_state: enforcing
crypto_policies_policy: "DEFAULT:NO-SHA1"
crypto_policies_reload: true
tlog_scope_sssd: all
aide_install: true
aide_init: true
aide_generate_config: true
...
