---
- name: Sync a satellite repository
  hosts: "{{ target | default('satellite') }}"
  gather_facts: false
  tasks:
    - name: Synchronize a Satellite repository
      redhat.satellite.repository_sync:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        organization: "{{ satellite_org_name }}"
        product: "{{ item }}"
        validate_certs: false
      loop: "{{ satellite_product }}"
...
