---
- name: Install all windows updates without rebooting
  hosts: all
  gather_facts: false
  tasks:
    - name: Install windows updates
      ansible.windows.win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates #default
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates #default
          - ServicePacks
          - Tools
          - UpdateRollups #default
          - Updates
          - Upgrades
        log_path: C:\ansible_win_updates.txt
        reboot: true
...