---
- name: Watch a URL for site availability
  hosts: all
  sources:
    - name: Check a URL
      ansible.eda.url_check:
        urls:
          - "{{ url_check_target }}"
        delay: 120
        verify_ssl: false

  rules:
    - name: Redeploy site with current content
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "{{ url_check_jt_name }}"
          organization: "{{ url_check_org }}"
