---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Listen for a webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Push event to repository
      condition: event.payload.repository.name == "{{ repo_name }}"
      action:
        run_job_template:
          name: deploy_site.yml
          organization: HomeLab
          job_args:
            extra_vars:
              application_repo: "{{ repo_name }}"
